# Basic Python
# 1. Split this string

In [2]:
msg = "Hi IBM!"

In [3]:
msg = msg.split()
msg

['Hi', 'IBM!']

# 2. Use .format() to print the following string
## Output should be: The diameter of Earth is 12742 kilometers.

In [4]:
planet = "Earth"
diameter = 12742

In [5]:
var = "The diameter of {planet} is {diameter} kilometers".format(planet = "Earth",diameter = 12742)
var

'The diameter of Earth is 12742 kilometers'

## 3. In this nest dictionary grab the word "hello"

In [6]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [7]:
print(d['k1'][3]['tricky'][3]['target'][3])

hello


# Numpy

In [8]:
import numpy as npy

## 4.1 Create an array of 20 zeros?
## 4.2 Create an array of 16 eight?

In [9]:
arr = npy.zeros(20)
print("The array of 20 zeros are:")
print(arr)

The array of 20 zeros are:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [10]:
arr = npy.ones(16)*8
print("The array of 16 Eight are:")
print(arr)

The array of 16 Eight are:
[8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]


## 5. Create an array of all the even integers from 50 to 100

In [11]:
arr = npy.arange(50,100,2)
print("Array of all the even integers from 50 to 100 are:")
print(arr)

Array of all the even integers from 50 to 100 are:
[50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96
 98]


## 6. Create a 4x4 matrix with values ranging from 0 to 16

In [13]:
var =  npy.arange(0, 16).reshape(4,4)
print(var)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


## 7. Concatenate a and b
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [14]:
a = npy.array([1, 2, 3]) 
b = npy.array([4, 5, 6])
c = npy.concatenate([a,b])
c

array([1, 2, 3, 4, 5, 6])

# Pandas
## 8. Create a dataframe with 3 rows and 2 columns

In [16]:
import pandas as pd
data = [['Sanjay', 19], ['Kannan', 20], ['Divert', 15]]
df = pd.DataFrame(data, columns=['Name', 'Age'])
print(df)

     Name  Age
0  Sanjay   19
1  Kannan   20
2  Divert   15


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [18]:
pd.date_range(start='1/9/2022', end='1/10/2022')

DatetimeIndex(['2022-01-09', '2022-01-10'], dtype='datetime64[ns]', freq='D')

## 10. Create 2D list to DataFrame

In [19]:
lists = [[1, 'xxx', 21], [2, 'yyy', 24], [3, 'zzz', 25]]
df = pd.DataFrame(lists, columns =['S.No', 'Name', 'Age']) 
df

S.No Name  Age
0     1  xxx   21
1     2  yyy   24
2     3  zzz   25